---
title: "Introduction"
date: 2022-03-31
---

title: Gecko Blog
author: Bence-D
email: -hidden-
description: > # A fresh blog about geckos. That's about it.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
